.\"
.\" Copyright (c) 2013-2020 David Demelier <markand@malikania.fr>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd @IRCCD_MAN_DATE@
.Dt IRCCD-API-CHRONO 3
.Os
.\" NAME
.Sh NAME
.Nm Irccd.Chrono
.Nd irccd chrono API
.\" SYNOPSIS
.Sh SYNOPSIS
.Fn Irccd.Chrono
.Vt Irccd.Chrono.prototype.elapsed
.Fn Irccd.Chrono.prototype.reset
.\" DESCRIPTION
.Sh DESCRIPTION
This module keeps track of elapsed time.
.\" METHODS
.Sh METHODS
.\" Irccd.Chrono
The
.Fn Irccd.Chrono
constructor function creates a chrono object at the current time.
.Pp
When constructed successfully, the object has the following properties:
.Pp
.Bl -tag -width 18n -offset indent -compact
.It Va elapsed No (int)
Return the number of milliseconds since creation or last call to
.El
.Pp
.\" Irccd.Chrono.prototype.reset
The
.Fn Irccd.Chrono.prototype.reset
method starts or restarts accumulating time.
.\" SEE ALSO
.Sh SEE ALSO
.Xr irccd-api 3
