.\"
.\" Copyright (c) 2013-2022 David Demelier <markand@malikania.fr>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd @IRCCD_MAN_DATE@
.Dt IRCCD-PLUGIN-ROULETTE 7
.Os
.\" NAME
.Sh NAME
.Nm roulette
.Nd irccd roulette plugin
.\" DESCRIPTION
.Sh DESCRIPTION
The
.Nm
plugin is a funny script that let you do a russian roulette game but without any
injuries.
.Pp
Note: the bot will perform a kick command if the user is being shot so you must
be sure to have channel operator mode set on irccd.
.\" INSTALLATION
.Sh INSTALLATION
The plugin
.Nm
is distributed with irccd. To enable it add it into your
.Xr irccd.conf 5
configuration file.
.Pp
.Bd -literal -offset indent
plugin "roulette"
.Ed
.\" USAGE
.Sh USAGE
The
.Nm
plugin simply reacts to the special command.
.Bd -literal -offset Ds
markand: !roulette
irccd: markand, you're lucky this time
markand: !roulette
irccd: markand, you're lucky this time
markand: !roulette
markand was kicked by irccd [markand, HEADSHOT]
.Ed
.\" TEMPLATES
.Sh TEMPLATES
The plugin
.Nm
supports the following templates properties:
.Bl -tag -width lucky
.It Va lucky
The text to show on luck. Keywords:
.Em count
(the number of turns left in the cylinder).
.It Va shot
The text to show on shot.
.El
.Pp
All templates supports the following standard keywords:
.Em channel , command , nickname , origin , plugin , server .
.\" EXAMPLES
.Sh EXAMPLES
Example of configuration file:
.Bd -literal
plugin "roulette" {
  templates {
    "lucky" "#{nickname} you're gonna get shot";
    "shot"  "BIM";
  }
}
.Ed
.\" SEE ALSO
.Sh SEE ALSO
.Xr irccd 1 ,
.Xr irccd-templates 7
