.\"
.\" Copyright (c) 2013-2021 David Demelier <markand@malikania.fr>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd @IRCCD_MAN_DATE@
.Dt IRCCD-PLUGIN-AUTH 7
.Os
.\" NAME
.Sh NAME
.Nm auth
.Nd irccd auth plugin
.\" DESCRIPTION
.Sh DESCRIPTION
The plugin
.Nm
provides generic authentication to the most popular services.
.Pp
For the moment,
.Nm auth
supports the following backends:
.Bl -tag -width nickserv
.It nickserv
the NickServ service, using /msg NickServ identify user pass
.It quakenet
the quakenet.org service, using /msg Q@CServe.quakenet.org AUTH user pass
.El
.\" INSTALLATION
.Sh INSTALLATION
The plugin
.Nm
is distributed with irccd. To enable it add it into your
.Xr irccd.conf 5
configuration file.
.Pp
.Bd -literal -offset indent
plugin "auth"
.Ed
.\" USAGE
.Sh USAGE
You must configure the file to enable authentication.
.\" CONFIGURATION
.Sh CONFIGURATION
The plugin
.Nm
support the following configuration properties:
.Bl -tag -width "server.password (string)"
.It Va server.type No (string)
Must be
.Em nickserv
or
.Em quakenet .
.It Va server.password No (string)
The password.
.It Va server.username No (string)
The username to use. Required for quakenet, optional for nickserv.
.El
.Pp
Note: you must replace server prefix with the server identifier you refer to in
the
.Xr irccd.conf 5
file.
.Pp
Example of configuration:
.Bd -literal
plugin "auth" {
  config {
    "freenode.type"     "nickserv";
    "freenode.password" "mysecretpassword";
    "freenode.username" "jeanfrancois";

    "wanadoo.type"      "nickserv";
    "wanadoo.password"  "wanadoo is dead";
  }
}
.Ed
