set(
	PRIVATE_HEADERS
	${CMAKE_CURRENT_LIST_DIR}/connection.h
	${CMAKE_CURRENT_LIST_DIR}/directory.h
	${CMAKE_CURRENT_LIST_DIR}/elapsed-timer.h
	${CMAKE_CURRENT_LIST_DIR}/ini.h
	${CMAKE_CURRENT_LIST_DIR}/filesystem.h
	${CMAKE_CURRENT_LIST_DIR}/sockets.h
	${CMAKE_CURRENT_LIST_DIR}/xdg.h
)

set(
	PRIVATE_SOURCES
	${CMAKE_CURRENT_LIST_DIR}/connection.cpp
	${CMAKE_CURRENT_LIST_DIR}/directory.cpp
	${CMAKE_CURRENT_LIST_DIR}/elapsed-timer.cpp
	${CMAKE_CURRENT_LIST_DIR}/ini.cpp
	${CMAKE_CURRENT_LIST_DIR}/filesystem.cpp
	${CMAKE_CURRENT_LIST_DIR}/sockets.cpp
	${CMAKE_CURRENT_LIST_DIR}/xdg.cpp
)
