.\"
.\" Copyright (c) 2013-2022 David Demelier <markand@malikania.fr>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd @IRCCD_MAN_DATE@
.Dt IRCCD-PLUGIN-ASK 7
.Os
.\" NAME
.Sh NAME
.Nm ask
.Nd irccd ask plugin
.\" DESCRIPTION
.Sh DESCRIPTION
The plugin
.Nm
is funny script that helps you in your life. It will tell you if you will be
rich, famous and so on.
.\" INSTALLATION
.Sh INSTALLATION
The plugin
.Nm
is distributed with irccd. To enable it add it into your
.Xr irccd.conf 5
configuration file.
.Pp
.Bd -literal -offset indent
plugin "ask"
.Ed
.\" USAGE
.Sh USAGE
The plugin
.Nm
reacts to special command, you just need to do !ask the question and it will
give you a response.
.Pp
Example:
.Bd -literal
markand: !ask will I be rich?
irccd: markand, No.
.Ed
.\" FILE
.Sh FILE
By default,
.Nm ask
will only answer yes or no. It's possible to add any answers you want in the
file
.Pa answers.conf
located in the ask configuration directory.
.Pp
Just add one line per answer like this (e.g.
.Pa @CMAKE_INSTALL_FULL_SYSCONFDIR@/irccd/plugin/ask/answers.conf ) .
.Bd -literal -offset Ds
Stop dreaming,
Definitely sure!
Maybe
.Ed
.\" CONFIGURATION
.Sh CONFIGURATION
The plugin
.Nm
supports the following configuration properties:
.Bl -tag -width "file (string)"
.It Va file No (string)
the path to the database file (Optional, default: answers.conf in configuration
directory).
.El
.\" SEE ALSO
.Sh SEE ALSO
.Xr irccd 1 ,
.Xr irccd-templates 7
